--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-27-2017   
--------------------------------------------------------
REM INSERTING into HR.TB_RECORD_DETAILS
SET DEFINE OFF;
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (2,12,'x',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (1,1,'Y',3,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (1,2,'Y',3,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (1,3,'N',4,2);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (1,4,'Y',3,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (1,5,'Y',3,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,3,'Y',3,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,1,'Y',1,1);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,2,'Y',2,2);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,4,'N',0,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,5,'N',0,2);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,6,'N',0,1);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,7,'Y',5,5);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,8,'N',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,9,'N',0,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,10,'N',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,11,'Y',5,5);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (12,12,'N',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,1,'Y',1,1);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,2,'N',0,2);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,3,'Y',3,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,4,'N',0,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,5,'N',0,2);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,6,'N',0,1);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,7,'N',0,5);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,8,'N',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,9,'N',0,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,10,'N',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,11,'N',0,5);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (13,12,'N',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (8,12,'x',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (11,12,'N',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,1,'N',0,1);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,2,'Y',2,2);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,3,'Y',3,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,4,'Y',3,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,5,'Y',2,2);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,6,'N',0,1);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,7,'N',0,5);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,8,'N',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,9,'N',0,3);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,10,'N',0,4);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,11,'N',0,5);
Insert into HR.TB_RECORD_DETAILS (RECORD_NO,QUIZ_NO,RECORD_RESULT,RECORD_ANSWER,QUIZ_ANSWER) values (14,12,'N',0,4);
